image: jangrewe/gitlab-ci-android

before_script:
- export GRADLE_USER_HOME=`pwd`/.gradle
- mkdir -p $GRADLE_USER_HOME
- chmod +x ./gradlew
- chmod +x ./check.sh
- chmod +x ./build.sh
- chmod +x ./build_customer.sh
- chmod +x ./deploy.sh
- chmod +x ./deploy_customer.sh

cache:
  key: ${CI_PROJECT_ID}
  paths:
  - .gradle/wrapper
  - .gradle/caches

stages:
- build
- check

build_and_deploy:
  stage: build
  script:
  - ./build.sh
  - ./deploy.sh
  only:
  - develop
  tags:
  - docker

build_and_deploy_customer:
  stage: build
  script:
  - ./build_customer.sh
  - ./deploy_customer.sh
  only:
  - customer
  artifacts:
    paths:
    - app/build/outputs/apk/prod
    expire_in: 1 week
  tags:
  - docker

build:
  stage: build
  script:
  - ./build.sh
  except:
    - develop
    - customer
  artifacts:
    paths:
    - app/build/outputs/apk/stage/qa
    expire_in: 1 week
  tags:
  - docker

check:
  stage: check
  script: ./check.sh
  only:
    - develop
  tags:
  - docker
